version: '3.9'

services:
  api:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    entrypoint: >
      sh -c "
        python test_task/manage.py migrate
        python test_task/manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${USERNAME_DB}"
      POSTGRES_PASSWORD: "${PASSWORD_DB}"


  #   # healthcheck:
  #   #   test: ["CMD-SHELL", "pg_isready", "-U", "$USERNAME_DB", "-d", "${DATABASE_NAME}"]
  #   #   interval: 10s
  #   #   timeout: 30s
  #   #   retries: 5
  #   #   start_period: 80s
    expose:
      - 5432

    ports:
      - $PORT_DB:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
