# Generated by Django 5.0.4 on 2024-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
