# Generated by Django 5.0.4 on 2024-04-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='api.referral'),
        ),
    ]
